version: '3.5'

services:

    # Services
    exchange:
        restart: always
        container_name: exchangeservice
        build: ./exchange
        depends_on:
            - database
        links:
            - database
        ports:
            - 50051:50051
        environment:
            MICRO_SERVER_ADDRESS: ":50051"
            DB_HOST: "database"
            DB_USER: "root"
            DB_PASS: "password"
            DB_NAME: "exchange-analytics"
            DB_PORT: "3306"
    
    # API Service
    analytics:
        restart: always
        container_name: analyticsApp
        build: ./analytics
        ports:
            - 50052:50052
    
    database:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_PASSWORD: "password"
        ports:
            - 3306:3306
